### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by bedrekarthik** [SDWebImage/SDWebImageLottiePlugin#4]
Hi,

Can we have SPM support with plugin for Lottie 2? i.e from current master branch.

cc: @dreampiggy

**Comment by dimabiserov** [comment]
yes. please

**Comment by dreampiggy** [comment]
SPM support it's OK.

For Lottie 2 vs Lottie 3, is that performance regression fixed ? #1 

If so, I can publish 1.0 version (for Lottie 3 dependency), and keep 0.x version use Lottie 2

**Comment by dimabiserov** [comment]
> SPM support it's OK.
> 
> For Lottie 2 vs Lottie 3, is that performance regression fixed ? #1
> 
> If so, I can publish 1.0 version (for Lottie 3 dependency), and keep 0.x version use Lottie 2

I made two new projects.
In one, I used your pod with lottie ~2.5

the second used lottie from the official github

and your poe works smoother
if you can do smooth with lottie 3 it's cool, if not, then 2.5 is fine)
